name: Build iOS Engine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup depot-tools
        uses: newkdev/setup-depot-tools@v1.0.1
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 17
          distribution: oracle
      - name: Get Ninja
        uses: turtlesec-no/get-ninja@1.1.0
      - name: Run gclient
        env:
          scheme: ${{ 'default' }}
        run: |
          echo "solutions=[{\"managed\":False,\"name\":\"src/flutter\",\"url\":\"git@github.com:SKKbySSK/engine.git\",\"custom_deps\":{},\"deps_file\":\"DEPS\",\"safesync_url\":\"\",\"custom_vars\":{\"use_cipd_goma\": True,},}]" > .gclient
          gclient sync
      - name: Prepare Device-Side
        run: ./flutter/tools/gn --ios --unoptimized --xcode-symlinks
      - name: Prepare Host-Side
        run: ./flutter/tools/gn --unoptimized --xcode-symlinks
      - name: Build Engine
        run: ninja -C out/ios_debug_unopt && ninja -C out/host_debug_unopt
